CREATE TABLE CARS (
    ID  INTEGER  PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR (50) NOT NULL ,
    MODEL VARCHAR (50) NOT NULL ,
    COLOR VARCHAR (50) NOT NULL ,
    YEAR_OF_PRODUCTION INTEGER (4),
    CAR_TYPE varchar (50) NOT NULL ,
    CONSTRAINT CAR_INFO_UC UNIQUE (BRAND, MODEL, COLOR, YEAR_OF_PRODUCTION, CAR_TYPE),
);